using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace CPL_Case_mini_capstone.Model
{


    /// <summary>
    /// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
    /// </summary>
    public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
    {

        /// <summary>
        /// Constructor.
        /// </summary>
        public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) :
                base(service)
        {
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="CPL_Case_mini_capstone.Model.Account"/> entities.
        /// </summary>
        public System.Linq.IQueryable<CPL_Case_mini_capstone.Model.Account> AccountSet
        {
            get
            {
                return this.CreateQuery<CPL_Case_mini_capstone.Model.Account>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="CPL_Case_mini_capstone.Model.Contact"/> entities.
        /// </summary>
        public System.Linq.IQueryable<CPL_Case_mini_capstone.Model.Contact> ContactSet
        {
            get
            {
                return this.CreateQuery<CPL_Case_mini_capstone.Model.Contact>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="CPL_Case_mini_capstone.Model.Incident"/> entities.
        /// </summary>
        public System.Linq.IQueryable<CPL_Case_mini_capstone.Model.Incident> IncidentSet
        {
            get
            {
                return this.CreateQuery<CPL_Case_mini_capstone.Model.Incident>();
            }
        }
    }
}
#pragma warning restore CS1591
